CREATE TABLE IF NOT EXISTS STUDENT(
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);
INSERT INTO STUDENT (ROLL_NO,NAME,ADDRESS,PHONE,AGE)VALUES
('1','RAV','DELHI','*****',18),
('2','RAM','GUJARAT','****',18),
('3','AMAN','DELHI','****',20),
('4','SUJIT','DELHI','****',18),
('5','RAVI','DELHI','****',18),
('6','HARSH','DELHI','****',20);
SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DELHI';
SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';
SELECT * FROM STUDENT WHERE NAME='RAM' OR NAME='SUJIT';
SELECT * FROM STUDENT WHERE NAME = 'RAM' OR AGE = 20;
SELECT * FROM STUDENT WHERE AGE=18 AND(NAME='RAM' OR NAME ='RAV');
