file = open("sample.txt","r")
content = file.read()
print(content)
file.write("Hi! this is shruti s student of grade 9")
file2 = open("sample2.txt","a")
content= file1.read()
file2.write(content)
file1.close()
file2.close()