file_read = open('sample.txt','r')
print("File in read mode")
print(file_read.read())
file_read.closee()
file_write = open('sample.txt','w')
file_write.write("File in write mode..")
file_write.write("Hi iam shruti")
file_write.close()
file_append = open('sample.txt','a')
file_append.write("\n File in append mode")
file_append.write("hi iam shruti")
file_append.close()